name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#        image: demo-app/my-project
#        tags: v1
#        registry: danpar.jfrog.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
    - name: Declare Jfrog
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

    - name: Collect
      run: |
        jf rt ping
        jf rt build-collect-env $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
        jf rt build-add-dependencies $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER  ./
        jf rt build-add-git $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
        
    - name: Deploy
      run: |
        jf rt jf rt u '(*).tgz' spring-libs-release/ --recursive=false
        
    - name: Publish
      run: |
        jf rt build-publish $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
        
        
        
